[project]
name = "weatherapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "llm-ollama>=0.9.1",
    "py2exe>=0.13.0.2",
    "pyinstaller>=6.13.0",
    "pytest>=8.3.5",
    "python-weather>=2.0.7",
    "smartfunc>=0.2.0",
    "termcolor>=3.0.1",
]

[project.optional-dependencies]
test = [
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.0",
    "pytest-cov>=6.0.0",
    "pytest-html>=4.1.1",
    "pytest-timeout>=2.3.1",
    "PyYAML>=6.0.2",
    "httpx>=0.28.1",
]

[tool.coverage.run]
source = ["lib", "main"]
branch = true
omit = ["tests/*", "setup.py"]

[tool.coverage.report]
show_missing = true
skip_covered = false
